version: "2.7"

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/recurrences_grpc
    ports:
      - 4400:4400
    command: cargo run --bin recurrences-server
